version: "2"

services:
  mongo:
    image: mongo:3.3
    container_name: mongo.test
    ports:
        - "27017:27017"
    networks:
      - reporting-network

volumes:
  reporting-var:

networks:
  reporting-network:
    driver: bridge
