version: "3"

services:

  search:
    image: registry.tools.trood.ru/search:${TAG_NAME:-dev}
    build:
      context: ./search
      dockerfile: Dockerfile
    container_name: search
    restart: always
    environment:
      AUTH_URL: "AUTH_URL"
      AUTH_DOMAIN: "SEARCH"
      AUTH_SECRET: "AUTH_SECRET"
      WHITE_URLS: ""
      SPHINX_DB: "mysql://sphinxsearch:9306/"
      SENTRY_ENABLED: "False"
      SENTRY_DSN: "YOUR_DNS_HERE"
    volumes:
      - ./search:/app
    networks:
      - search_net
    ports:
      - "8000:8000"
  
  sphinxsearch:
    image: registry.tools.trood.ru/sphinxsearch:${TAG_NAME:-dev}
    build:
      context: ./sphinxsearch
      dockerfile: Dockerfile
    container_name: sphinxsearch
    restart: always
    environment:
      SQL_QUERY: "SQL query should contain id"
      SQL_ATTR_BOOL: "attrs, separated, with, comma"
      SQL_ATTR_UINT: "attrs, separated, with, comma"
      SQL_FIELD_STRING: "attrs, separated, with, comma"
      INDEX_NAME: "INDEX_NAME"
      DB_USER: "DB_USER"
      DB_PASSWORD: "DB_PASSWORD"
      DB_HOST: "DB_PASSWORD"
      DB_NAME: "DB_PASSWORD"
      DB_PORT: "5432"
    networks:
      - search_net
    ports:
      - "9306:9306"

networks:
  search_net:
    driver: bridge
